package azul

import "context"

// ============================================================================
// Sale
// ============================================================================

// SaleRequest contains the parameters for a card-present or card-not-present sale.
type SaleRequest struct {
	// CardNumber is the full card number (e.g. "4111111111111111").
	CardNumber string

	// Expiration is the card expiration in YYYYMM format (e.g. "202512").
	Expiration string

	// CVC is the card security code (CVV2/CVC).
	CVC string

	// Amount is the total transaction amount including tax (e.g. 1500.00).
	Amount float64

	// ITBIS is the tax amount. Set to 0 if exempt or already included in Amount.
	ITBIS float64

	// OrderNumber is a reference number for this transaction.
	OrderNumber string

	// CustomOrderId is an optional merchant-assigned identifier.
	// Required if you plan to use VerifyPayment.
	CustomOrderId string

	// CurrencyPosCode overrides APIConfig.CurrencyPosCode for this request.
	// "$" = DOP, "USD" = US Dollar. Leave empty for the config default.
	CurrencyPosCode string

	// SaveToDataVault instructs Azul to tokenize the card.
	// When true, the response includes DataVaultToken.
	SaveToDataVault bool

	// ForceNo3DS skips 3D Secure verification when true.
	ForceNo3DS bool

	// Payments is the number of installments (cuotas). Defaults to "1".
	Payments string

	// Plan is the installment plan code. Defaults to "0".
	Plan string

	// AltMerchantName overrides Config.AltMerchantName for this request.
	AltMerchantName string
}

// Sale processes a card sale (TrxType="Sale") through Azul's ProcessPayment method.
//
// This captures the transaction immediately for settlement. It can only be voided
// within 20 minutes of approval.
//
// Example:
//
//	resp, err := client.Sale(ctx, azul.SaleRequest{
//	    CardNumber:  "4111111111111111",
//	    Expiration:  "202812",
//	    CVC:         "123",
//	    Amount:      1500.00,
//	    ITBIS:       0,
//	    OrderNumber: "ORD-1234",
//	})
func (c *APIClient) Sale(ctx context.Context, req SaleRequest) (*APIResponse, error) {
	currency := req.CurrencyPosCode
	if currency == "" {
		currency = c.config.CurrencyPosCode
	}

	altName := req.AltMerchantName
	if altName == "" {
		altName = c.config.AltMerchantName
	}

	payments := req.Payments
	if payments == "" {
		payments = "1"
	}
	plan := req.Plan
	if plan == "" {
		plan = "0"
	}

	payload := map[string]string{
		"Channel":              c.config.Channel,
		"Store":                c.config.Store,
		"CardNumber":           req.CardNumber,
		"Expiration":           req.Expiration,
		"CVC":                  req.CVC,
		"PosInputMode":         c.config.PosInputMode,
		"TrxType":              "Sale",
		"Amount":               FormatAmount(req.Amount),
		"Itbis":                FormatAmount(req.ITBIS),
		"CurrencyPosCode":      currency,
		"Payments":             payments,
		"Plan":                 plan,
		"AcquirerRefData":      "1",
		"RRN":                  "",
		"CustomerServicePhone": c.config.CustomerServicePhone,
		"OrderNumber":          req.OrderNumber,
		"ECommerceUrl":         c.config.ECommerceURL,
		"CustomOrderId":        req.CustomOrderId,
		"DataVaultToken":       "",
		"SaveToDataVault":      boolToAzul(req.SaveToDataVault),
		"ForceNo3DS":           boolToAzul(req.ForceNo3DS),
		"AltMerchantName":      altName,
	}

	return c.doRequest(ctx, "", payload)
}

// ============================================================================
// TokenSale
// ============================================================================

// TokenSaleRequest contains the parameters for a sale using a DataVault token.
type TokenSaleRequest struct {
	// DataVaultToken is the token previously generated by Azul.
	DataVaultToken string

	// CVC is optional for token sales — depends on merchant agreement with Azul.
	// Leave empty if CVC is not required.
	CVC string

	// Amount is the total transaction amount including tax.
	Amount float64

	// ITBIS is the tax amount. Set to 0 if exempt.
	ITBIS float64

	// OrderNumber is a reference number for this transaction.
	OrderNumber string

	// CustomOrderId is an optional merchant-assigned identifier.
	CustomOrderId string

	// CurrencyPosCode overrides APIConfig.CurrencyPosCode for this request.
	CurrencyPosCode string

	// ForceNo3DS skips 3D Secure verification when true.
	ForceNo3DS bool

	// Payments is the number of installments. Defaults to "1".
	Payments string

	// Plan is the installment plan code. Defaults to "0".
	Plan string

	// AltMerchantName overrides Config.AltMerchantName for this request.
	AltMerchantName string
}

// TokenSale processes a sale using a DataVault token (TrxType="Sale").
//
// The card number and expiration are sent as empty strings since the token
// replaces the card data. CVC is optional depending on the merchant's
// agreement with Azul.
//
// Example:
//
//	resp, err := client.TokenSale(ctx, azul.TokenSaleRequest{
//	    DataVaultToken: "6EF85D01-B07C-4E67-99F7-4E13A449DCDD",
//	    Amount:         500.00,
//	    ITBIS:          0,
//	    OrderNumber:    "ORD-5678",
//	})
func (c *APIClient) TokenSale(ctx context.Context, req TokenSaleRequest) (*APIResponse, error) {
	currency := req.CurrencyPosCode
	if currency == "" {
		currency = c.config.CurrencyPosCode
	}

	altName := req.AltMerchantName
	if altName == "" {
		altName = c.config.AltMerchantName
	}

	payments := req.Payments
	if payments == "" {
		payments = "1"
	}
	plan := req.Plan
	if plan == "" {
		plan = "0"
	}

	payload := map[string]string{
		"Channel":              c.config.Channel,
		"Store":                c.config.Store,
		"CardNumber":           "",
		"Expiration":           "",
		"CVC":                  req.CVC,
		"PosInputMode":         c.config.PosInputMode,
		"TrxType":              "Sale",
		"Amount":               FormatAmount(req.Amount),
		"Itbis":                FormatAmount(req.ITBIS),
		"CurrencyPosCode":      currency,
		"Payments":             payments,
		"Plan":                 plan,
		"AcquirerRefData":      "1",
		"RRN":                  "",
		"CustomerServicePhone": c.config.CustomerServicePhone,
		"OrderNumber":          req.OrderNumber,
		"ECommerceUrl":         c.config.ECommerceURL,
		"CustomOrderId":        req.CustomOrderId,
		"DataVaultToken":       req.DataVaultToken,
		"SaveToDataVault":      "0",
		"ForceNo3DS":           boolToAzul(req.ForceNo3DS),
		"AltMerchantName":      altName,
	}

	return c.doRequest(ctx, "", payload)
}

// ============================================================================
// Hold
// ============================================================================

// HoldRequest contains the parameters for a pre-authorization (hold).
type HoldRequest struct {
	// CardNumber is the full card number.
	CardNumber string

	// Expiration is the card expiration in YYYYMM format.
	Expiration string

	// CVC is the card security code.
	CVC string

	// Amount is the total amount to hold.
	Amount float64

	// ITBIS is the tax amount. Set to 0 if exempt.
	ITBIS float64

	// OrderNumber is a reference number for this transaction.
	OrderNumber string

	// CustomOrderId is an optional merchant-assigned identifier.
	CustomOrderId string

	// CurrencyPosCode overrides the config default.
	CurrencyPosCode string

	// SaveToDataVault instructs Azul to tokenize the card.
	SaveToDataVault bool

	// ForceNo3DS skips 3D Secure verification when true.
	ForceNo3DS bool

	// AltMerchantName overrides Config.AltMerchantName for this request.
	AltMerchantName string
}

// Hold processes a pre-authorization (TrxType="Hold") through Azul's ProcessPayment.
//
// A Hold reserves the amount on the cardholder's account without capturing it.
// Holds that are not posted have no time limit to be voided.
//
// Example:
//
//	resp, err := client.Hold(ctx, azul.HoldRequest{
//	    CardNumber:  "4111111111111111",
//	    Expiration:  "202812",
//	    CVC:         "123",
//	    Amount:      2000.00,
//	    ITBIS:       0,
//	    OrderNumber: "ORD-HOLD-1",
//	})
func (c *APIClient) Hold(ctx context.Context, req HoldRequest) (*APIResponse, error) {
	currency := req.CurrencyPosCode
	if currency == "" {
		currency = c.config.CurrencyPosCode
	}

	altName := req.AltMerchantName
	if altName == "" {
		altName = c.config.AltMerchantName
	}

	payload := map[string]string{
		"Channel":              c.config.Channel,
		"Store":                c.config.Store,
		"CardNumber":           req.CardNumber,
		"Expiration":           req.Expiration,
		"CVC":                  req.CVC,
		"PosInputMode":         c.config.PosInputMode,
		"TrxType":              "Hold",
		"Amount":               FormatAmount(req.Amount),
		"Itbis":                FormatAmount(req.ITBIS),
		"CurrencyPosCode":      currency,
		"Payments":             "1",
		"Plan":                 "0",
		"AcquirerRefData":      "1",
		"RRN":                  "",
		"CustomerServicePhone": c.config.CustomerServicePhone,
		"OrderNumber":          req.OrderNumber,
		"ECommerceUrl":         c.config.ECommerceURL,
		"CustomOrderId":        req.CustomOrderId,
		"DataVaultToken":       "",
		"SaveToDataVault":      boolToAzul(req.SaveToDataVault),
		"ForceNo3DS":           boolToAzul(req.ForceNo3DS),
		"AltMerchantName":      altName,
	}

	return c.doRequest(ctx, "", payload)
}

// ============================================================================
// TokenHold
// ============================================================================

// TokenHoldRequest contains the parameters for a pre-authorization using a DataVault token.
type TokenHoldRequest struct {
	// DataVaultToken is the token previously generated by Azul.
	DataVaultToken string

	// CVC is optional for token holds — depends on merchant agreement with Azul.
	CVC string

	// Amount is the total amount to hold.
	Amount float64

	// ITBIS is the tax amount. Set to 0 if exempt.
	ITBIS float64

	// OrderNumber is a reference number for this transaction.
	OrderNumber string

	// CustomOrderId is an optional merchant-assigned identifier.
	CustomOrderId string

	// CurrencyPosCode overrides APIConfig.CurrencyPosCode for this request.
	CurrencyPosCode string

	// ForceNo3DS skips 3D Secure verification when true.
	ForceNo3DS bool

	// AltMerchantName overrides Config.AltMerchantName for this request.
	AltMerchantName string
}

// TokenHold processes a pre-authorization using a DataVault token (TrxType="Hold").
//
// Similar to Hold, but uses a previously tokenized card instead of raw card data.
// The card number and expiration are sent as empty strings since the token
// replaces the card data.
//
// A TokenHold reserves the amount on the cardholder's account without capturing it.
// Use Post to capture the held amount later.
//
// Example:
//
//	resp, err := client.TokenHold(ctx, azul.TokenHoldRequest{
//	    DataVaultToken: "6EF85D01-B07C-4E67-99F7-4E13A449DCDD",
//	    Amount:         2000.00,
//	    ITBIS:          0,
//	    OrderNumber:    "ORD-HOLD-TOKEN-1",
//	})
//	if resp.IsApproved() {
//	    // Later, capture with client.Post(ctx, PostRequest{AzulOrderId: resp.AzulOrderId, ...})
//	}
func (c *APIClient) TokenHold(ctx context.Context, req TokenHoldRequest) (*APIResponse, error) {
	currency := req.CurrencyPosCode
	if currency == "" {
		currency = c.config.CurrencyPosCode
	}

	altName := req.AltMerchantName
	if altName == "" {
		altName = c.config.AltMerchantName
	}

	payload := map[string]string{
		"Channel":              c.config.Channel,
		"Store":                c.config.Store,
		"CardNumber":           "",
		"Expiration":           "",
		"CVC":                  req.CVC,
		"PosInputMode":         c.config.PosInputMode,
		"TrxType":              "Hold",
		"Amount":               FormatAmount(req.Amount),
		"Itbis":                FormatAmount(req.ITBIS),
		"CurrencyPosCode":      currency,
		"Payments":             "1",
		"Plan":                 "0",
		"AcquirerRefData":      "1",
		"RRN":                  "",
		"CustomerServicePhone": c.config.CustomerServicePhone,
		"OrderNumber":          req.OrderNumber,
		"ECommerceUrl":         c.config.ECommerceURL,
		"CustomOrderId":        req.CustomOrderId,
		"DataVaultToken":       req.DataVaultToken,
		"SaveToDataVault":      "0",
		"ForceNo3DS":           boolToAzul(req.ForceNo3DS),
		"AltMerchantName":      altName,
	}

	return c.doRequest(ctx, "", payload)
}

// ============================================================================
// Refund
// ============================================================================

// RefundRequest contains the parameters for a refund (devolución).
type RefundRequest struct {
	// CardNumber is the full card number.
	CardNumber string

	// Expiration is the card expiration in YYYYMM format.
	Expiration string

	// CVC is the card security code.
	CVC string

	// Amount is the refund amount.
	Amount float64

	// ITBIS is the tax amount to refund. Set to 0 if not applicable.
	ITBIS float64

	// OriginalDate is the date of the original transaction in YYYYMMDD format.
	// Required by Azul to locate the original transaction.
	OriginalDate string

	// AzulOrderId is the Azul-assigned order ID from the original transaction.
	// Required by Azul to locate the original transaction.
	AzulOrderId string

	// OrderNumber is a reference number for this refund.
	OrderNumber string

	// CustomOrderId is an optional merchant-assigned identifier.
	CustomOrderId string

	// CurrencyPosCode overrides the config default.
	CurrencyPosCode string

	// AltMerchantName overrides Config.AltMerchantName for this request.
	AltMerchantName string
}

// Refund processes a refund (TrxType="Refund") through Azul's ProcessPayment.
//
// Use Refund to return funds to the cardholder after the original Sale has been
// settled (more than 20 minutes after approval). For transactions within 20
// minutes, use Void instead.
//
// OriginalDate and AzulOrderId are required fields — Azul uses them to locate
// the original transaction being refunded.
//
// Example:
//
//	resp, err := client.Refund(ctx, azul.RefundRequest{
//	    CardNumber:   "4111111111111111",
//	    Expiration:   "202812",
//	    CVC:          "123",
//	    Amount:       500.00,
//	    ITBIS:        0,
//	    OriginalDate: "20250115",
//	    AzulOrderId:  "11350",
//	    OrderNumber:  "ORD-REFUND-1",
//	})
func (c *APIClient) Refund(ctx context.Context, req RefundRequest) (*APIResponse, error) {
	currency := req.CurrencyPosCode
	if currency == "" {
		currency = c.config.CurrencyPosCode
	}

	altName := req.AltMerchantName
	if altName == "" {
		altName = c.config.AltMerchantName
	}

	payload := map[string]string{
		"Channel":              c.config.Channel,
		"Store":                c.config.Store,
		"CardNumber":           req.CardNumber,
		"Expiration":           req.Expiration,
		"CVC":                  req.CVC,
		"PosInputMode":         c.config.PosInputMode,
		"TrxType":              "Refund",
		"Amount":               FormatAmount(req.Amount),
		"Itbis":                FormatAmount(req.ITBIS),
		"CurrencyPosCode":      currency,
		"Payments":             "1",
		"Plan":                 "0",
		"AcquirerRefData":      "",
		"RRN":                  "",
		"CustomerServicePhone": c.config.CustomerServicePhone,
		"OrderNumber":          req.OrderNumber,
		"ECommerceUrl":         c.config.ECommerceURL,
		"CustomOrderId":        req.CustomOrderId,
		"OriginalDate":         req.OriginalDate,
		"AzulOrderId":          req.AzulOrderId,
		"DataVaultToken":       "",
		"SaveToDataVault":      "0",
		"ForceNo3DS":           "0",
		"AltMerchantName":      altName,
	}

	return c.doRequest(ctx, "", payload)
}
