package azul

import (
	"context"
	"encoding/json"
	"fmt"
)

// ============================================================================
// CreateSubscription (recurringsubscriptioncreate)
// ============================================================================

// SubscriptionRequest contains the parameters to create a recurring payment subscription.
//
// This endpoint has important differences from other API methods:
//   - Amount uses DECIMAL format: 50.00 = fifty pesos (NOT cents like ProcessPayment)
//   - Currency uses "DOP" (not "$" like other methods)
//   - Card expiration field is "CardExpiration" (not "Expiration")
//   - Booleans are JSON native (true/false), not "0"/"1"
//   - Nullable fields (MaxRepeats, backup cards) are sent as JSON null
type SubscriptionRequest struct {
	// CardNumber is the full card number.
	CardNumber string

	// CardExpiration is the card expiration in YYYYMM format (e.g., "202512").
	CardExpiration string

	// CVC is the card security code (CVV2/CVC).
	CVC string

	// Amount is the total subscription amount in DECIMAL format.
	// 50.00 = fifty pesos. This is different from other API methods that use cents format.
	Amount float64

	// ITBIS is the tax amount in decimal format. Set to 0 if exempt.
	ITBIS float64

	// Currency is "DOP" (Dominican Peso) or "USD". Defaults to "DOP".
	// NOTE: Uses "DOP" not "$" like other API methods.
	Currency string

	// Frequency determines how often the subscription is charged.
	// Valid values: "Daily", "Weekly", "MonthlyByDay".
	Frequency string

	// EveryXDays: for Daily frequency, process every X days (e.g., "2" = every 2 days).
	EveryXDays string

	// EveryXWeeks: for Weekly frequency, process every X weeks (e.g., "1" = every week).
	EveryXWeeks string

	// Weekdays: for Weekly frequency, day of week to process (e.g., "3" = Wednesday).
	Weekdays string

	// EveryXMonths: for Monthly frequency, process every X months (e.g., "1" = monthly).
	EveryXMonths string

	// DayOfMonth: for Monthly frequency, day of month to process (e.g., "27").
	DayOfMonth string

	// Month: month number for scheduling (e.g., "7" = July).
	Month string

	// EveryXYears: optional, process every X years.
	EveryXYears string

	// MaxRepeats is the max number of recurring charges. Leave empty for unlimited.
	MaxRepeats string

	// StartDate is the subscription start date. Required. Format: "YYYY-M-D" (e.g., "2022-7-27").
	StartDate string

	// EndDate is the optional subscription end date.
	EndDate string

	// CustomerName is the customer's full name. Required.
	CustomerName string

	// CustomerContract is the subscription/contract number. Required.
	CustomerContract string

	// CustomerIdentType is the document type (e.g., "Cedula"). Required.
	CustomerIdentType string

	// CustomerIdentNum is the document number (e.g., "00100204566"). Required.
	CustomerIdentNum string

	// CustomerSubscriptionId is an optional token/ID generated by Azul.
	CustomerSubscriptionId string

	// CustomerEmail is the customer email. Required if enabling email notifications.
	CustomerEmail string

	// NotifyTransactions enables email notifications on charge attempts.
	NotifyTransactions bool

	// NotifyExpired enables notification when card expires.
	NotifyExpired bool

	// NotifyNearExpired enables notification when card is about to expire.
	NotifyNearExpired bool

	// NotifyPhone includes merchant phone number in notifications.
	NotifyPhone bool

	// NotificationPhone is the merchant's phone number for notifications.
	NotificationPhone string

	// Description is an optional comment or note for the subscription.
	Description string

	// SaveToDataVault tokenizes the card during subscription creation.
	SaveToDataVault bool

	// Card2Number is an optional backup card number (Azul tries this if primary fails).
	Card2Number string

	// Card2Expiration is the backup card expiration (MMYY format).
	Card2Expiration string

	// Card3Number is an optional second backup card number.
	Card3Number string

	// Card3Expiration is the second backup card expiration (MMYY format).
	Card3Expiration string
}

// SubscriptionResponse represents the response from Azul's recurringsubscriptioncreate endpoint.
type SubscriptionResponse struct {
	CustomSubscriptionId string `json:"CustomSubscriptionId"`
	ErrorDescription     string `json:"ErrorDescription"`
	NextScheduledDate    string `json:"NextScheduledDate"`
	ResponseCode         string `json:"ResponseCode"`
}

// WasCreated returns true if the subscription was successfully created (ResponseCode "CREATED").
func (r *SubscriptionResponse) WasCreated() bool {
	return r.ResponseCode == "CREATED"
}

// HasError returns true if there was an error creating the subscription.
func (r *SubscriptionResponse) HasError() bool {
	return r.ErrorDescription != ""
}

// subscriptionPayload is the internal JSON structure sent to Azul.
// Uses mixed types (float64, bool, *string for null) unlike other endpoints
// that use map[string]string.
type subscriptionPayload struct {
	Channel                               string  `json:"Channel"`
	Store                                 string  `json:"Store"`
	CardNumber                            string  `json:"CardNumber"`
	CardExpiration                        string  `json:"CardExpiration"`
	CVC                                   string  `json:"CVC"`
	Amount                                float64 `json:"Amount"`
	Itbis                                 float64 `json:"Itbis"`
	Currency                              string  `json:"Currency"`
	MaxRepeats                            *string `json:"MaxRepeats"`
	Frequency                             string  `json:"Frequency"`
	FrequencyParamEveryXDays              string  `json:"FrequencyParamEveryXDays"`
	FrequencyParamEveryXWeeks             string  `json:"FrequencyParamEveryXWeeks"`
	FrequencyParamWeekdays                string  `json:"FrequencyParamWeekdays"`
	FrequencyParamEveryXMonths            string  `json:"FrequencyParamEveryXMonths"`
	FrequencyParamEveryXYears             string  `json:"FrequencyParamEveryXYears"`
	FrequencyParamDay                     string  `json:"FrequencyParamDay"`
	FrequencyParamMonth                   string  `json:"FrequencyParamMonth"`
	CustomerSubscriptionId                string  `json:"CustomerSubscriptionId"`
	SaveToDataVault                       int     `json:"SaveToDataVault"`
	CustomerName                          string  `json:"CustomerName"`
	CustomerContract                      string  `json:"CustomerContract"`
	CustomerIdentType                     string  `json:"CustomerIdentType"`
	CustomerIdentNum                      string  `json:"CustomerIdentNum"`
	CustomerEmail                         string  `json:"CustomerEmail"`
	CustomerEmailNotificationsTrx         bool    `json:"CustomerEmailNotificationsTrx"`
	CustomerEmailNotificationsExpired     bool    `json:"CustomerEmailNotificationsExpired"`
	CustomerEmailNotificationsNearExpired bool    `json:"CustomerEmailNotificationsNearExpired"`
	CustomerEmailNotificationsPhone       bool    `json:"CustomerEmailNotificationsPhone"`
	CustomerEmailNotificationsPhoneNumber string  `json:"CustomerEmailNotificationsPhoneNumber"`
	Description                           string  `json:"Description"`
	StartDate                             string  `json:"StartDate"`
	EndDate                               string  `json:"EndDate"`
	Card2Number                           *string `json:"Card2Number"`
	Card2Expiration                       *string `json:"Card2Expiration"`
	Card3Number                           *string `json:"Card3Number"`
	Card3Expiration                       *string `json:"Card3Expiration"`
}

// CreateSubscription creates a recurring payment subscription through Azul's
// recurringsubscriptioncreate endpoint.
//
// Subscriptions can be configured as daily, weekly, or monthly recurring charges.
// Azul automatically processes the charges at the specified frequency.
//
// The endpoint is: base URL + "?recurringsubscriptioncreate"
//
// IMPORTANT: This endpoint uses different data formats than other API methods:
//   - Amount is decimal (50.00 = fifty pesos), NOT cents (5000)
//   - Currency is "DOP" or "USD", NOT "$"
//   - Azul may require separate Auth1/Auth2 credentials for subscriptions in production
//
// Example (daily every 2 days):
//
//	resp, err := client.CreateSubscription(ctx, azul.SubscriptionRequest{
//	    CardNumber:     "5426111111111979",
//	    CardExpiration: "202512",
//	    CVC:            "123",
//	    Amount:         50.00,
//	    ITBIS:          0,
//	    Frequency:      "Daily",
//	    EveryXDays:     "2",
//	    Month:          "7",
//	    StartDate:      "2025-7-27",
//	    MaxRepeats:     "12",
//	    CustomerName:       "Juan Pérez",
//	    CustomerContract:   "WEB1234",
//	    CustomerIdentType:  "Cedula",
//	    CustomerIdentNum:   "00100204566",
//	})
//	if resp.WasCreated() {
//	    fmt.Println("Suscripción creada, próximo cobro:", resp.NextScheduledDate)
//	}
func (c *APIClient) CreateSubscription(ctx context.Context, req SubscriptionRequest) (*SubscriptionResponse, error) {
	currency := req.Currency
	if currency == "" {
		currency = "DOP"
	}

	var maxRepeats *string
	if req.MaxRepeats != "" {
		mr := req.MaxRepeats
		maxRepeats = &mr
	}

	var card2Num, card2Exp, card3Num, card3Exp *string
	if req.Card2Number != "" {
		card2Num = &req.Card2Number
		card2Exp = &req.Card2Expiration
	}
	if req.Card3Number != "" {
		card3Num = &req.Card3Number
		card3Exp = &req.Card3Expiration
	}

	saveToDataVault := 0
	if req.SaveToDataVault {
		saveToDataVault = 1
	}

	payload := subscriptionPayload{
		Channel:                               c.config.Channel,
		Store:                                 c.config.Store,
		CardNumber:                            req.CardNumber,
		CardExpiration:                        req.CardExpiration,
		CVC:                                   req.CVC,
		Amount:                                req.Amount,
		Itbis:                                 req.ITBIS,
		Currency:                              currency,
		MaxRepeats:                            maxRepeats,
		Frequency:                             req.Frequency,
		FrequencyParamEveryXDays:              req.EveryXDays,
		FrequencyParamEveryXWeeks:             req.EveryXWeeks,
		FrequencyParamWeekdays:                req.Weekdays,
		FrequencyParamEveryXMonths:            req.EveryXMonths,
		FrequencyParamEveryXYears:             req.EveryXYears,
		FrequencyParamDay:                     req.DayOfMonth,
		FrequencyParamMonth:                   req.Month,
		CustomerSubscriptionId:                req.CustomerSubscriptionId,
		SaveToDataVault:                       saveToDataVault,
		CustomerName:                          req.CustomerName,
		CustomerContract:                      req.CustomerContract,
		CustomerIdentType:                     req.CustomerIdentType,
		CustomerIdentNum:                      req.CustomerIdentNum,
		CustomerEmail:                         req.CustomerEmail,
		CustomerEmailNotificationsTrx:         req.NotifyTransactions,
		CustomerEmailNotificationsExpired:     req.NotifyExpired,
		CustomerEmailNotificationsNearExpired: req.NotifyNearExpired,
		CustomerEmailNotificationsPhone:       req.NotifyPhone,
		CustomerEmailNotificationsPhoneNumber: req.NotificationPhone,
		Description:                           req.Description,
		StartDate:                             req.StartDate,
		EndDate:                               req.EndDate,
		Card2Number:                           card2Num,
		Card2Expiration:                       card2Exp,
		Card3Number:                           card3Num,
		Card3Expiration:                       card3Exp,
	}

	respBody, err := c.doRequestRaw(ctx, "recurringsubscriptioncreate", payload)
	if err != nil {
		return nil, err
	}

	var result SubscriptionResponse
	if err := json.Unmarshal(respBody, &result); err != nil {
		return nil, fmt.Errorf("azul: failed to decode subscription response: %w", err)
	}

	return &result, nil
}
